time: 0-40:00:00
interactive_debug_session: false
runner: research.conditional.train.cc_train

n_gpus: 1

params:
  name: "kanmoe_naive"
  save_weights_interval: -1
  tags: [kan]

  logger_types: "neptune"
  project_name: pmtest/llm-random

  fsdp_enabled: false
  fsdp_selective_precision_modules: "AttentionMechanism,MoeGating,RoPE,ExpertGatingOld,TokenChoiceRouterOld"
  batch_size: 32
  cutoff: 1024
  final_lr_fraction: 0.1
  scheduler: cosine
  final_lr_step: 50000
  n_steps: 50000
  lr_warmup_steps: 5000
  grad_clip: 1.0
  weight_decay: 0.01
  learning_rate: 2e-4
  logging_interval_heavy: 5000
  logging_interval_loss: 1000
  mixed_precision: true
  mixed_precision_dtype: bfloat16
  torch_compile: false
  loss_checkpoint_chungs: 2

  dataset_type: c4

  # MODEL
  model_type: gpt
  activation_type: relu
  dmodel: 768
  n_att_heads: 12
  n_blocks: 12

  # medium size (otherwise cuda out of memory error)
  dmodel: 512
  dff: 2048
  n_att_heads: 8
  n_blocks: 8

  # moe
  # n_experts: 8
  effective_dff_x: 4
  expansion_rate: 8
  granularity: 1
  ff_mode: token_choice
  ^moe_inner_expert: [kan, ff_gated]
  use_torch_bmm: true
  softmax_over: experts
  group_granular_moe_by_batch: true
  granular_moe_one_hot_impl: true
  ^layer_norm_in_expert_choice: [true]
  zloss_weight: 0

  # init
  init_scale: 0.1
  init_type: truncated_normal

  # debug
  # logger_types: "stdout"
  # use_dummy_dataset: true
  # n_blocks: 1
  # dmodel: 16
  # n_att_heads: 1


# parent: configs/baselines/gpt/dense/base.yaml
# md5_parent_hash: 763f39978a58f704200275285162594c
# time: "40:00:00"
# n_gpus: 1

# params:
#   # tokenizer: gpt

#   name: "zloss_may_help_here"
#   # fsdp_enabled: true
#   mixed_precision: true
#   mixed_precision_dtype: bfloat16
#   flash_attention: true
#   # fsdp_modules_to_wrap: "TransformerBlock,EmbeddingLayer,PredictionHead"
#   # activation_checkpointing_modules: "TransformerBlock,EmbeddingLayer,PredictionHead"
#   gradient_accumulation_steps: 4
#   grad_clip: 1.0

#   # lr_ratio_modules: ["logging_ff_pre_relu.weight", "logging_ff_post_relu.weight", "attention.output_projection.weight"]
#   # lr_ratios: [2, 0.2, 0.2]
#   tags: ["zloss"]

#   n_steps: 37500
#   learning_rate: 1e-3
#   lr_warmup_steps: 375
#   final_lr_step: 37500
#   weight_decay: 0.01
#   scheduler: "cosine"
#   decoding_interval: 0
#   logging_interval_heavy: 10000
#   init_type: truncated_normal
#   init_scale: 0.1
#   save_weights_interval: 0
#   batch_size: 128
#   cutoff: 1024
#   dataset_type: c4

#   ^zloss_weight: [0, 0.0001]